# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test on supported Python version by GitHub Actions

on:
  push:
    branches: [ master, prova-2.7 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: python -m pip install -r requirements-dev.txt -r requirements.txt
    - name: Check Types
      run: ./scripts/check-types
    - name: Run tests
      run: python -m pytest
