# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Test on Python 2.7

on:
  push:
    branches: [ master, prova-2.7 ]
  pull_request:
    branches: [ master, prova-2.7 ]

jobs:
  build:
    # the hack used to run this job with python 2.7 is explained here:
    # https://github.com/actions/setup-python/issues/672#issuecomment-1589120020
    runs-on: ubuntu-20.04
    container:
      image: python:2.7-buster

    steps:
    - uses: actions/checkout@v3
    - run: id -a
    - run: pwd
    - run: groups
    - run: ls -la
    - name: set up user
      run: |
        useradd runner --shell=/bin/bash --create-home
        export PATH="/home/runner/.local/bin:$PATH"
        su - runner -c 'python -m pip install --upgrade pip'
        su - runner -c 'python -m pip install -r requirements-dev.txt -r requirements.txt'
        su - runner -c 'python -m pip freeze'
        su - runner -c 'python -m pytest'
